-- Create profiles table for user data
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  display_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create movies table with comprehensive movie data
CREATE TABLE public.movies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  release_year INTEGER,
  genre TEXT,
  poster_url TEXT,
  trailer_url TEXT,
  imdb_rating DECIMAL(3,1),
  runtime_minutes INTEGER,
  director TEXT,
  cast_members TEXT[],
  country TEXT,
  awards TEXT,
  streaming_platforms TEXT[],
  price_inr DECIMAL(10,2),
  is_premium BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create watchlist table
CREATE TABLE public.watchlist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movie_id UUID NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
  added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, movie_id)
);

-- Create purchased_movies table
CREATE TABLE public.purchased_movies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movie_id UUID NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
  stripe_payment_intent_id TEXT,
  amount_paid DECIMAL(10,2),
  purchased_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, movie_id)
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watchlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchased_movies ENABLE ROW LEVEL SECURITY;

-- RLS Policies for profiles
CREATE POLICY "profiles_select_own" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- RLS Policies for movies (public read access)
CREATE POLICY "movies_select_all" ON public.movies FOR SELECT USING (true);

-- RLS Policies for watchlist
CREATE POLICY "watchlist_select_own" ON public.watchlist FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "watchlist_insert_own" ON public.watchlist FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "watchlist_delete_own" ON public.watchlist FOR DELETE USING (auth.uid() = user_id);

-- RLS Policies for purchased_movies
CREATE POLICY "purchased_select_own" ON public.purchased_movies FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "purchased_insert_own" ON public.purchased_movies FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Create function for automatic timestamp updates
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for automatic timestamp updates
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_movies_updated_at BEFORE UPDATE ON public.movies FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Insert 100 real movies with Indian prices and posters
INSERT INTO public.movies (title, description, release_year, genre, poster_url, trailer_url, imdb_rating, runtime_minutes, director, cast_members, country, price_inr, streaming_platforms) VALUES 
('The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 1994, 'Drama', 'https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=NmzuHjWmXOc', 9.3, 142, 'Frank Darabont', ARRAY['Tim Robbins', 'Morgan Freeman'], 'USA', 299.00, ARRAY['Netflix', 'Prime Video']),
('The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 1972, 'Crime', 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzUwODI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=UaVTIH8mujA', 9.2, 175, 'Francis Ford Coppola', ARRAY['Marlon Brando', 'Al Pacino'], 'USA', 399.00, ARRAY['Prime Video']),
('The Dark Knight', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.', 2008, 'Action', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=EXeTwQWrcwY', 9.0, 152, 'Christopher Nolan', ARRAY['Christian Bale', 'Heath Ledger'], 'USA', 349.00, ARRAY['Netflix', 'HBO Max']),
('Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.', 1994, 'Crime', 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=s7EdQ4FqbhY', 8.9, 154, 'Quentin Tarantino', ARRAY['John Travolta', 'Uma Thurman'], 'USA', 299.00, ARRAY['Prime Video']),
('Schindlers List', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.', 1993, 'Drama', 'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=gG22XNhtnoY', 9.0, 195, 'Steven Spielberg', ARRAY['Liam Neeson', 'Ralph Fiennes'], 'USA', 449.00, ARRAY['Netflix']),
('The Lord of the Rings: The Return of the King', 'Gandalf and Aragorn lead the World of Men against Saurons army to draw his gaze from Frodo and Sam as they approach Mount Doom.', 2003, 'Adventure', 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWI5MTktXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=r5X-hFf6Bwo', 9.0, 201, 'Peter Jackson', ARRAY['Elijah Wood', 'Viggo Mortensen'], 'New Zealand', 399.00, ARRAY['HBO Max', 'Prime Video']),
('Fight Club', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club.', 1999, 'Drama', 'https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=qtRKdVHc-cE', 8.8, 139, 'David Fincher', ARRAY['Brad Pitt', 'Edward Norton'], 'USA', 249.00, ARRAY['Netflix']),
('Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man.', 1994, 'Drama', 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=bLvqoHBptjg', 8.8, 142, 'Robert Zemeckis', ARRAY['Tom Hanks', 'Robin Wright'], 'USA', 299.00, ARRAY['Prime Video']),
('Inception', 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.', 2010, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=YoHD9XEInc0', 8.8, 148, 'Christopher Nolan', ARRAY['Leonardo DiCaprio', 'Marion Cotillard'], 'USA', 349.00, ARRAY['Netflix', 'HBO Max']),
('The Matrix', 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth.', 1999, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=vKQi3bBA1y8', 8.7, 136, 'Lana Wachowski', ARRAY['Keanu Reeves', 'Laurence Fishburne'], 'USA', 299.00, ARRAY['HBO Max']),
('Goodfellas', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill.', 1990, 'Crime', 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=qo5jJpHtI1Y', 8.7, 146, 'Martin Scorsese', ARRAY['Robert De Niro', 'Ray Liotta'], 'USA', 349.00, ARRAY['Prime Video']),
('Star Wars: Episode IV - A New Hope', 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy.', 1977, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg', 'https://www.youtube.com/watch?v=vZ734NWnAHA', 8.6, 121, 'George Lucas', ARRAY['Mark Hamill', 'Harrison Ford'], 'USA', 299.00, ARRAY['Disney+']),
('The Silence of the Lambs', 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.', 1991, 'Thriller', 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=W6Mm8Sbe__o', 8.6, 118, 'Jonathan Demme', ARRAY['Jodie Foster', 'Anthony Hopkins'], 'USA', 279.00, ARRAY['Prime Video']),
('Saving Private Ryan', 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.', 1998, 'War', 'https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=9CiW_DgxCnQ', 8.6, 169, 'Steven Spielberg', ARRAY['Tom Hanks', 'Matt Damon'], 'USA', 349.00, ARRAY['Prime Video']),
('The Green Mile', 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape.', 1999, 'Drama', 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg', 'https://www.youtube.com/watch?v=Ki4haFrqSrw', 8.6, 189, 'Frank Darabont', ARRAY['Tom Hanks', 'Michael Clarke Duncan'], 'USA', 299.00, ARRAY['Netflix']),
('Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.', 2014, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=zSWdZVtXT7E', 8.6, 169, 'Christopher Nolan', ARRAY['Matthew McConaughey', 'Anne Hathaway'], 'USA', 399.00, ARRAY['HBO Max']),
('Casablanca', 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband.', 1942, 'Romance', 'https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=BkL9l7qovsE', 8.5, 102, 'Michael Curtiz', ARRAY['Humphrey Bogart', 'Ingrid Bergman'], 'USA', 199.00, ARRAY['HBO Max']),
('The Departed', 'An undercover cop and a police informant play a cat and mouse game with each other while infiltrating an Irish gang.', 2006, 'Crime', 'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg', 'https://www.youtube.com/watch?v=auYbpnEwBBg', 8.5, 151, 'Martin Scorsese', ARRAY['Leonardo DiCaprio', 'Matt Damon'], 'USA', 329.00, ARRAY['Netflix']),
('The Prestige', 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion.', 2006, 'Mystery', 'https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg', 'https://www.youtube.com/watch?v=o4gHCmTQDVI', 8.5, 130, 'Christopher Nolan', ARRAY['Hugh Jackman', 'Christian Bale'], 'USA', 299.00, ARRAY['Netflix']),
('Gladiator', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.', 2000, 'Action', 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=owK1qxDselE', 8.5, 155, 'Ridley Scott', ARRAY['Russell Crowe', 'Joaquin Phoenix'], 'USA', 329.00, ARRAY['Prime Video']),
('The Lion King', 'A Lion cub crown prince is tricked by a treacherous uncle into thinking he caused his fathers death.', 1994, 'Animation', 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNjMtMmE4Mjg5MGUwYTFkXkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=lFzVJEksoDY', 8.5, 88, 'Roger Allers', ARRAY['Matthew Broderick', 'Jeremy Irons'], 'USA', 249.00, ARRAY['Disney+']),
('Back to the Future', 'Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean.', 1985, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=qvsgGtivCgs', 8.5, 116, 'Robert Zemeckis', ARRAY['Michael J. Fox', 'Christopher Lloyd'], 'USA', 249.00, ARRAY['Netflix']),
('Apocalypse Now', 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel.', 1979, 'War', 'https://m.media-amazon.com/images/M/MV5BMDdkYjJjMjItMzgwNy00NDcxLTk1NjktYTJjZmQ5NDkwZDE1XkEyXkFqcGdeQXVyNTAxNTc4OTY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=FTjG-Aux_yQ', 8.4, 147, 'Francis Ford Coppola', ARRAY['Martin Sheen', 'Marlon Brando'], 'USA', 349.00, ARRAY['Prime Video']),
('The Terminator', 'A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine.', 1984, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=k64P4l2Wmeg', 8.1, 107, 'James Cameron', ARRAY['Arnold Schwarzenegger', 'Linda Hamilton'], 'USA', 229.00, ARRAY['Prime Video']),
('Alien', 'The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.', 1979, 'Horror', 'https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=jQ5lPt9edzQ', 8.5, 117, 'Ridley Scott', ARRAY['Sigourney Weaver', 'Tom Skerritt'], 'USA', 299.00, ARRAY['HBO Max']);

-- Continue with more movies (25 added so far, need 75 more)
INSERT INTO public.movies (title, description, release_year, genre, poster_url, trailer_url, imdb_rating, runtime_minutes, director, cast_members, country, price_inr, streaming_platforms) VALUES 
('Titanic', 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', 1997, 'Romance', 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=2e-eXJ6HgkQ', 7.9, 194, 'James Cameron', ARRAY['Leonardo DiCaprio', 'Kate Winslet'], 'USA', 329.00, ARRAY['Prime Video']),
('Avatar', 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world.', 2009, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=5PSNL1qE6VY', 7.9, 162, 'James Cameron', ARRAY['Sam Worthington', 'Zoe Saldana'], 'USA', 399.00, ARRAY['Disney+']),
('Avengers: Endgame', 'After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos.', 2019, 'Action', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=TcMBFSGVi1c', 8.4, 181, 'Russo Brothers', ARRAY['Robert Downey Jr.', 'Chris Evans'], 'USA', 399.00, ARRAY['Disney+']),
('Spider-Man: Into the Spider-Verse', 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals.', 2018, 'Animation', 'https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=tg52up16eq0', 8.4, 117, 'Bob Persichetti', ARRAY['Shameik Moore', 'Jake Johnson'], 'USA', 279.00, ARRAY['Netflix']),
('Joker', 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society.', 2019, 'Drama', 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=zAGVQLHvwOY', 8.4, 122, 'Todd Phillips', ARRAY['Joaquin Phoenix', 'Robert De Niro'], 'USA', 349.00, ARRAY['HBO Max']),
('Parasite', 'A poor family schemes to become employed by a wealthy family by infiltrating their household and posing as unrelated, highly qualified individuals.', 2019, 'Thriller', 'https://m.media-amazon.com/images/M/MV5BYWZjMjJmZTItOWFkNC00NGUzLThhMzUtNjlkNmJjY2RjOGM1XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=5xH0HfJHsaY', 8.5, 132, 'Bong Joon-ho', ARRAY['Song Kang-ho', 'Lee Sun-kyun'], 'South Korea', 279.00, ARRAY['Hulu']),
('1917', 'Two British soldiers are tasked with delivering a critical message to call off a doomed attack during World War I.', 2019, 'War', 'https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLWE1ZDAtMTZjOWMyNmIwMmRhXkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=YqNYrYUiMfg', 8.2, 119, 'Sam Mendes', ARRAY['George MacKay', 'Dean-Charles Chapman'], 'UK', 329.00, ARRAY['Prime Video']),
('Once Upon a Time in Hollywood', 'A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywoods Golden Age.', 2019, 'Drama', 'https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=ELeMaP8EPAA', 7.6, 161, 'Quentin Tarantino', ARRAY['Leonardo DiCaprio', 'Brad Pitt'], 'USA', 349.00, ARRAY['Netflix']),
('Mad Max: Fury Road', 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland.', 2015, 'Action', 'https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=hEJnMQG9ev8', 8.1, 120, 'George Miller', ARRAY['Tom Hardy', 'Charlize Theron'], 'Australia', 299.00, ARRAY['HBO Max']),
('Blade Runner 2049', 'A young blade runner discovers a long-buried secret that leads him to track down former blade runner Rick Deckard.', 2017, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=gCcx85zbxz4', 8.0, 164, 'Denis Villeneuve', ARRAY['Ryan Gosling', 'Harrison Ford'], 'USA', 349.00, ARRAY['Prime Video']),
('Dune', 'Feature adaptation of Frank Herberts science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset.', 2021, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=n9xhJrPXop4', 8.0, 155, 'Denis Villeneuve', ARRAY['Timothée Chalamet', 'Rebecca Ferguson'], 'USA', 399.00, ARRAY['HBO Max']),
('The Batman', 'When the Riddler, a sadistic serial killer, begins murdering key political figures in Gotham, Batman is forced to investigate the citys hidden corruption.', 2022, 'Action', 'https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=mqqft2x_Aa4', 7.8, 176, 'Matt Reeves', ARRAY['Robert Pattinson', 'Zoë Kravitz'], 'USA', 399.00, ARRAY['HBO Max']),
('Top Gun: Maverick', 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, training a new generation for a specialized mission.', 2022, 'Action', 'https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=qSqVVswa420', 8.3, 130, 'Joseph Kosinski', ARRAY['Tom Cruise', 'Miles Teller'], 'USA', 399.00, ARRAY['Prime Video']),
('No Time to Die', 'James Bond is enjoying a tranquil life in Jamaica after leaving active service when CIA agent Felix Leiter asks for help.', 2021, 'Action', 'https://m.media-amazon.com/images/M/MV5BYWQ2NzQ1NjktMzNkNS00MGY1LTgwMmMtYTllYTI5YzNmMmE0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=BIhNsAtPbPI', 7.3, 163, 'Cary Joji Fukunaga', ARRAY['Daniel Craig', 'Léa Seydoux'], 'UK', 399.00, ARRAY['Prime Video']),
('The French Dispatch', 'A love letter to journalists set in an outpost of an American newspaper in a fictional twentieth-century French city.', 2021, 'Comedy', 'https://m.media-amazon.com/images/M/MV5BNjQ2NDA3ODM2N15BMl5BanBnXkFtZTgwNzE2NDQ2NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=TcPk2p0Zaw4', 7.1, 107, 'Wes Anderson', ARRAY['Bill Murray', 'Frances McDormand'], 'USA', 279.00, ARRAY['Hulu']),
('Knives Out', 'A detective investigates the death of a patriarch of an eccentric, combative family.', 2019, 'Mystery', 'https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=qGqiHJTsRkQ', 7.9, 130, 'Rian Johnson', ARRAY['Daniel Craig', 'Chris Evans'], 'USA', 299.00, ARRAY['Prime Video']),
('Ford v Ferrari', 'American car designer Carroll Shelby and driver Ken Miles battle corporate interference to build a revolutionary race car for Ford.', 2019, 'Drama', 'https://m.media-amazon.com/images/M/MV5BM2QzM2JiNTMtODU2My00NzExLWE3NzMtOTY2OGY1OWVkMjkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=zyYgDtY2AMY', 8.1, 152, 'James Mangold', ARRAY['Matt Damon', 'Christian Bale'], 'USA', 349.00, ARRAY['HBO Max']),
('La La Land', 'A jazz musician and an aspiring actress meet and fall in love in Los Angeles while pursuing their dreams.', 2016, 'Romance', 'https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=0pdqf4P9MB8', 8.0, 128, 'Damien Chazelle', ARRAY['Ryan Gosling', 'Emma Stone'], 'USA', 299.00, ARRAY['Netflix']),
('The Grand Budapest Hotel', 'The adventures of Gustave H, a legendary concierge at a famous European hotel.', 2014, 'Comedy', 'https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=1Fg5iWmQjwk', 8.1, 99, 'Wes Anderson', ARRAY['Ralph Fiennes', 'F. Murray Abraham'], 'Germany', 279.00, ARRAY['Hulu']),
('Moonlight', 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood.', 2016, 'Drama', 'https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=9NJj12tJzqc', 7.4, 111, 'Barry Jenkins', ARRAY['Mahershala Ali', 'Naomie Harris'], 'USA', 249.00, ARRAY['Netflix']),
('Everything Everywhere All at Once', 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes.', 2022, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_SX300.jpg', 'https://www.youtube.com/watch?v=wxN1T1uxQ2g', 7.8, 139, 'Daniels', ARRAY['Michelle Yeoh', 'Stephanie Hsu'], 'USA', 349.00, ARRAY['Netflix']),
('The Shape of Water', 'At a top secret research facility, a lonely janitor forms a unique relationship with an amphibious creature.', 2017, 'Fantasy', 'https://m.media-amazon.com/images/M/MV5BNGNiNWQ5M2MtNGI0OC00MjM0LWJmYzEtODI5ZjFkMjU1YjQ5XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=XFYWazblaUA', 7.3, 123, 'Guillermo del Toro', ARRAY['Sally Hawkins', 'Octavia Spencer'], 'USA', 299.00, ARRAY['Hulu']),
('Get Out', 'A young African-American visits his white girlfriends parents for the weekend, where his simmering uneasiness becomes a nightmare.', 2017, 'Horror', 'https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=DzfpyUB60YY', 7.7, 104, 'Jordan Peele', ARRAY['Daniel Kaluuya', 'Allison Williams'], 'USA', 249.00, ARRAY['Prime Video']),
('A Quiet Place', 'A family is forced to live in silence while hiding from creatures that hunt by sound.', 2018, 'Horror', 'https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=WR7cc5t7tv8', 7.5, 90, 'John Krasinski', ARRAY['Emily Blunt', 'John Krasinski'], 'USA', 249.00, ARRAY['Prime Video']),
('Black Panther', 'TChalla, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future.', 2018, 'Action', 'https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=xjDjIWPwcPU', 7.3, 134, 'Ryan Coogler', ARRAY['Chadwick Boseman', 'Michael B. Jordan'], 'USA', 329.00, ARRAY['Disney+']),
('Wonder Woman', 'When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war.', 2017, 'Action', 'https://m.media-amazon.com/images/M/MV5BMTYzODQzYjQtNTczNC00MzZhLTg1ZWYtZDUxYmQ3ZTY4NzA1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=1Q8fG0TtVAY', 7.4, 141, 'Patty Jenkins', ARRAY['Gal Gadot', 'Chris Pine'], 'USA', 299.00, ARRAY['HBO Max']);

-- Continue with more movies (we now have 50, need 50 more)
INSERT INTO public.movies (title, description, release_year, genre, poster_url, trailer_url, imdb_rating, runtime_minutes, director, cast_members, country, price_inr, streaming_platforms) VALUES 
('Guardians of the Galaxy', 'A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.', 2014, 'Action', 'https://m.media-amazon.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_SX300.jpg', 'https://www.youtube.com/watch?v=d96cjJhvlMA', 8.0, 121, 'James Gunn', ARRAY['Chris Pratt', 'Zoe Saldana'], 'USA', 299.00, ARRAY['Disney+']),
('Doctor Strange', 'While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.', 2016, 'Action', 'https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=HSzx-zryEgM', 7.5, 115, 'Scott Derrickson', ARRAY['Benedict Cumberbatch', 'Chiwetel Ejiofor'], 'USA', 299.00, ARRAY['Disney+']),
('Thor: Ragnarok', 'Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök.', 2017, 'Action', 'https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=ue80QwXMRHg', 7.9, 130, 'Taika Waititi', ARRAY['Chris Hemsworth', 'Tom Hiddleston'], 'USA', 299.00, ARRAY['Disney+']),
('Captain America: The Winter Soldier', 'As Steve Rogers struggles to embrace his role in the modern world, he teams up with Natasha Romanoff.', 2014, 'Action', 'https://m.media-amazon.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=7SlILk2WMTI', 7.7, 136, 'Russo Brothers', ARRAY['Chris Evans', 'Scarlett Johansson'], 'USA', 299.00, ARRAY['Disney+']),
('Iron Man', 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor.', 2008, 'Action', 'https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=8ugaeA-nMTc', 7.9, 126, 'Jon Favreau', ARRAY['Robert Downey Jr.', 'Gwyneth Paltrow'], 'USA', 299.00, ARRAY['Disney+']),
('The Avengers', 'Earths mightiest heroes must come together and learn to fight as a team to stop the mischievous Loki.', 2012, 'Action', 'https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=eOrNdBpGMv8', 8.0, 143, 'Joss Whedon', ARRAY['Robert Downey Jr.', 'Chris Evans'], 'USA', 329.00, ARRAY['Disney+']),
('Ant-Man', 'Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength.', 2015, 'Action', 'https://m.media-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=pWdKf3MneyI', 7.3, 117, 'Peyton Reed', ARRAY['Paul Rudd', 'Evangeline Lilly'], 'USA', 279.00, ARRAY['Disney+']),
('Captain Marvel', 'Carol Danvers becomes one of the universes most powerful heroes when Earth is caught in the middle of a galactic war.', 2019, 'Action', 'https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=Z1BCujX3pw8', 6.8, 123, 'Anna Boden', ARRAY['Brie Larson', 'Samuel L. Jackson'], 'USA', 299.00, ARRAY['Disney+']),
('Shang-Chi and the Legend of the Ten Rings', 'Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.', 2021, 'Action', 'https://m.media-amazon.com/images/M/MV5BNTliYjlkNDQtMjFlNS00NjgzLWFmMWEtYmM2Mzc2Zjg3ZjEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=8YjFbMbfXaQ', 7.4, 132, 'Destin Daniel Cretton', ARRAY['Simu Liu', 'Awkwafina'], 'USA', 349.00, ARRAY['Disney+']),
('Eternals', 'The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.', 2021, 'Action', 'https://m.media-amazon.com/images/M/MV5BY2Y1ODBhNzktNzNiOS00NjgxLWJiMzYtN2U5YWQwMWQ2ZGYwXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_SX300.jpg', 'https://www.youtube.com/watch?v=x_me3xsvDgk', 6.3, 156, 'Chloé Zhao', ARRAY['Gemma Chan', 'Richard Madden'], 'USA', 349.00, ARRAY['Disney+']),
('Spider-Man: No Way Home', 'With Spider-Mans identity now revealed, Peter asks Doctor Strange for help.', 2021, 'Action', 'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=JfVOs4VSpmA', 8.2, 148, 'Jon Watts', ARRAY['Tom Holland', 'Zendaya'], 'USA', 399.00, ARRAY['Netflix']),
('The Irishman', 'A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa.', 2019, 'Crime', 'https://m.media-amazon.com/images/M/MV5BMGUyM2ZiZmUtMWY0OC00NTQ4LThkOGUtNjY2NjkzMDJiMWMwXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=WHXxVmeGQUc', 7.8, 209, 'Martin Scorsese', ARRAY['Robert De Niro', 'Al Pacino'], 'USA', 399.00, ARRAY['Netflix']),
('Marriage Story', 'A stage director and his actor wife struggle through a grueling coast-to-coast divorce.', 2019, 'Drama', 'https://m.media-amazon.com/images/M/MV5BZGVmY2RjNDgtMTc3Yy00YmY0LTgwODItYzBjNWJhNTRlYjdkXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=BHi-a1n8t7M', 7.9, 137, 'Noah Baumbach', ARRAY['Adam Driver', 'Scarlett Johansson'], 'USA', 299.00, ARRAY['Netflix']),
('Roma', 'A year in the life of a middle-class familys maid in Mexico City in the early 1970s.', 2018, 'Drama', 'https://m.media-amazon.com/images/M/MV5BMTU2ODQ3NjMyMV5BMl5BanBnXkFtZTgwNzE4NDM3NjM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=6BS27ngZtxg', 7.7, 135, 'Alfonso Cuarón', ARRAY['Yalitza Aparicio', 'Marina de Tavira'], 'Mexico', 249.00, ARRAY['Netflix']),
('The Two Popes', 'Behind Vatican walls, the conservative Pope Benedict XVI and the liberal future Pope Francis must find common ground.', 2019, 'Drama', 'https://m.media-amazon.com/images/M/MV5BYjEzMTM2NjAtNjYzZi00MzkwLWJjNjYtNTc3ZmNiZGI5NTVjXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=T5OhkFY1PQE', 7.6, 125, 'Fernando Meirelles', ARRAY['Anthony Hopkins', 'Jonathan Pryce'], 'UK', 279.00, ARRAY['Netflix']),
('Mank', 'The story of the man who wrote Citizen Kane, Herman J. Mankiewicz.', 2020, 'Drama', 'https://m.media-amazon.com/images/M/MV5BMTIzZWM2OTUtOTFjNy00YWI5LWE2N2UtZjE2ZWUzZWM4ZjE4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=aSfBvvYKJXs', 6.8, 131, 'David Fincher', ARRAY['Gary Oldman', 'Amanda Seyfried'], 'USA', 299.00, ARRAY['Netflix']),
('The Trial of the Chicago 7', 'The story of 7 people on trial stemming from various charges surrounding the uprising at the 1968 Democratic National Convention.', 2020, 'Drama', 'https://m.media-amazon.com/images/M/MV5BNDFkZjA0NmEtNmY2ZC00NGI0LWJhYmYtMjJmYmZlMzU5N2IyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=aGfDyiBi5KE', 7.7, 129, 'Aaron Sorkin', ARRAY['Eddie Redmayne', 'Sacha Baron Cohen'], 'USA', 329.00, ARRAY['Netflix']),
('Da 5 Bloods', 'Four African American vets battle the forces of man and nature when they return to Vietnam seeking their lost treasure.', 2020, 'Drama', 'https://m.media-amazon.com/images/M/MV5BMTQ5ODMzNjUwNl5BMl5BanBnXkFtZTgwNzIwNDY2NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=s1Elo6C8u6k', 6.5, 154, 'Spike Lee', ARRAY['Delroy Lindo', 'Jonathan Majors'], 'USA', 329.00, ARRAY['Netflix']),
('The Platform', 'A vertical prison with one cell per level. Two people per cell. Only one food platform and two minutes per day to feed.', 2019, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMjYzZGMzOWItYWI1MC00YzI0LWEzZjItZGJhMWNhZWE5NzU3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=RlfooqeZcdY', 7.0, 94, 'Galder Gaztelu-Urrutia', ARRAY['Ivan Massagué', 'Zorion Eguileor'], 'Spain', 249.00, ARRAY['Netflix']),
('Extraction', 'Tyler Rake, a fearless black market mercenary, embarks on the most deadly extraction of his career.', 2020, 'Action', 'https://m.media-amazon.com/images/M/MV5BMjIwNzc1OTg5MV5BMl5BanBnXkFtZTgwNjg1NzAzMzE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=L6P3nI6VnlY', 6.7, 116, 'Sam Hargrave', ARRAY['Chris Hemsworth', 'Rudhraksh Jaiswal'], 'USA', 299.00, ARRAY['Netflix']),
('The Old Guard', 'A covert team of immortal mercenaries is suddenly exposed and must now fight to keep their identity a secret.', 2020, 'Action', 'https://m.media-amazon.com/images/M/MV5BNzliZjZkNGEtMmU1YS00NzBkLWEzNzEtODBhYjYyODE2ODc2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg', 'https://www.youtube.com/watch?v=aK-X2d0lJ_s', 6.6, 125, 'Gina Prince-Bythewood', ARRAY['Charlize Theron', 'KiKi Layne'], 'USA', 279.00, ARRAY['Netflix']),
('6 Underground', 'After faking his death, a tech billionaire recruits a team of international operatives for a bold and bloody mission.', 2019, 'Action', 'https://m.media-amazon.com/images/M/MV5BMTgwNjM4NDktZGE3NS00N2NmLTgyOWUtNzU4NjNmYWE4OWUwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=YLE1L2rKQSY', 6.1, 128, 'Michael Bay', ARRAY['Ryan Reynolds', 'Mélanie Laurent'], 'USA', 299.00, ARRAY['Netflix']),
('Project Power', 'On the streets of New Orleans, word begins to spread about a mysterious new pill that unlocks superpowers.', 2020, 'Action', 'https://m.media-amazon.com/images/M/MV5BOWJlZWE1NGEtOWJmOS00NTEzLWI5MDktNzM5OTE4NWJmNjczXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=_py__BS5_Fs', 6.0, 113, 'Henry Joost', ARRAY['Jamie Foxx', 'Joseph Gordon-Levitt'], 'USA', 279.00, ARRAY['Netflix']),
('Enola Holmes', 'When Enola Holmes, Sherlock Holmes teenage sister, discovers her mother has disappeared, she sets off to find her.', 2020, 'Mystery', 'https://m.media-amazon.com/images/M/MV5BNDZhZWJhODgtNmY1My00YmZhLTk5NGEtNGNlNGYwYzU0ZWQwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=3t1g2pa355k', 6.6, 123, 'Harry Bradbeer', ARRAY['Millie Bobby Brown', 'Henry Cavill'], 'USA', 249.00, ARRAY['Netflix']),
('The Midnight Sky', 'A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.', 2020, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BM2Q4YjMzZjAtYjYzNi00NTA3LTgzNDAtNDFjMTgxOGExYWIzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=v75BKTea7sM', 5.7, 118, 'George Clooney', ARRAY['George Clooney', 'Felicity Jones'], 'USA', 279.00, ARRAY['Netflix']);

-- Final 25 movies to reach 100
INSERT INTO public.movies (title, description, release_year, genre, poster_url, trailer_url, imdb_rating, runtime_minutes, director, cast_members, country, price_inr, streaming_platforms) VALUES 
('Bird Box', 'Five years after an ominous unseen presence drives most of society to suicide, a mother and her two children make a desperate bid for safety.', 2018, 'Horror', 'https://m.media-amazon.com/images/M/MV5BMjY0ODk2NjEyNV5BMl5BanBnXkFtZTgwMzkzNzk2NjM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=o2AsIXSh2xo', 6.6, 124, 'Susanne Bier', ARRAY['Sandra Bullock', 'Trevante Rhodes'], 'USA', 249.00, ARRAY['Netflix']),
('The Kissing Booth', 'A high school student is forced to confront her secret crush at a kissing booth.', 2018, 'Romance', 'https://m.media-amazon.com/images/M/MV5BMjQ4ZjcyYTYtZjExMC00NzA1LWJlOWItOGU0NzBjMjQ3ZWVjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=7zEd_et4_FU', 5.9, 105, 'Vince Marcello', ARRAY['Joey King', 'Jacob Elordi'], 'USA', 199.00, ARRAY['Netflix']),
('To All the Boys Ive Loved Before', 'A teenage girls secret love letters are exposed and wreak havoc on her love life.', 2018, 'Romance', 'https://m.media-amazon.com/images/M/MV5BMjQ3NjM5MTAzN15BMl5BanBnXkFtZTgwODQzMDAwNjM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=555oiY9RWM4', 7.0, 99, 'Susan Johnson', ARRAY['Lana Condor', 'Noah Centineo'], 'USA', 199.00, ARRAY['Netflix']),
('Set It Up', 'Two overworked and underpaid assistants come up with a plan to get their bosses off their backs by setting them up with each other.', 2018, 'Romance', 'https://m.media-amazon.com/images/M/MV5BMzU0NTM3MDEtZWY5ZS00NWU5LTkzOGMtZDY0NDI1M2I5N2IzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=d9HWKz2bGjE', 6.5, 105, 'Claire Scanlon', ARRAY['Zoey Deutch', 'Glen Powell'], 'USA', 199.00, ARRAY['Netflix']),
('Always Be My Maybe', 'Everyone assumed Sasha and Marcus would wind up together, except for Sasha and Marcus.', 2019, 'Romance', 'https://m.media-amazon.com/images/M/MV5BOTc2ZGU2NjAtNmI5ZS00MDE0LTk1MzEtMGFhNDRiZmQ3ODZjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=K2bBqMSiMgE', 6.8, 101, 'Nahnatchka Khan', ARRAY['Ali Wong', 'Randall Park'], 'USA', 199.00, ARRAY['Netflix']),
('The Half of It', 'A shy, straight-A Chinese-American student helps the sweet jock woo the girl they both secretly love.', 2020, 'Romance', 'https://m.media-amazon.com/images/M/MV5BNjE5ODU4NTctYWRiOS00ZTZmLWE2NzUtOGNkMmFiNzQ5YjY0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=B-yhF7IScUE', 6.9, 104, 'Alice Wu', ARRAY['Leah Lewis', 'Daniel Diemer'], 'USA', 199.00, ARRAY['Netflix']),
('Okja', 'A young girl risks everything to prevent a powerful, multinational company from kidnapping her best friend.', 2017, 'Adventure', 'https://m.media-amazon.com/images/M/MV5BMjQxMTMzNjI0NF5BMl5BanBnXkFtZTgwNzEyNjUwMTI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=AjCebKn4iic', 7.3, 120, 'Bong Joon-ho', ARRAY['Tilda Swinton', 'Paul Dano'], 'South Korea', 279.00, ARRAY['Netflix']),
('I Am Mother', 'A teenage girl is raised underground by a robot mother designed to repopulate the earth.', 2019, 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BZjY2YjdhMDUtMGYzZS00NmM4LWI4NTAtZmE3NGJkY2YyZGVlXkEyXkFqcGdeQXVyNTc5OTMwOTQ@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=N5BKctcZM64', 6.7, 113, 'Grant Sputore', ARRAY['Hilary Swank', 'Clara Rugaard'], 'Australia', 249.00, ARRAY['Netflix']),
('Cam', 'Alice, an ambitious camgirl, wakes up one day to discover shes been replaced on her show with an exact replica of herself.', 2018, 'Horror', 'https://m.media-amazon.com/images/M/MV5BM2Y3NzYzMGEtODZhMS00NWZhLTlkMjMtOWZiZGY1N2UzMzA3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=o2TWPF0t9w4', 5.9, 94, 'Daniel Goldhaber', ARRAY['Madeline Brewer', 'Patch Darragh'], 'USA', 199.00, ARRAY['Netflix']),
('In the Tall Grass', 'After hearing a young boys cry for help, a sister and brother venture into a vast field of tall grass to rescue him.', 2019, 'Horror', 'https://m.media-amazon.com/images/M/MV5BNzNkNmQ2ZTYtODJlOC00NDU3LTg2YWYtMzlmZmVlN2M5YjFhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=DzVhkjoOKWM', 5.4, 101, 'Vincenzo Natali', ARRAY['Harrison Gilbertson', 'Laysla De Oliveira'], 'Canada', 199.00, ARRAY['Netflix']),
('The Ritual', 'A group of college friends reunite for a trip to the forest, but encounter a menacing presence in the woods.', 2017, 'Horror', 'https://m.media-amazon.com/images/M/MV5BMzYxMDQyOGQtNmJjOS00Y2RjLWE1YzItZGYxYjc4MTA3OGE0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=Vfugwq2uoa0', 6.3, 94, 'David Bruckner', ARRAY['Rafe Spall', 'Arsher Ali'], 'UK', 199.00, ARRAY['Netflix']),
('Cargo', 'After an epidemic spreads all over Australia, a father searches for someone willing to protect his daughter.', 2017, 'Drama', 'https://m.media-amazon.com/images/M/MV5BMjM5ZGVhZWEtNzVhOS00MWE1LWIwYmQtNGFhMjEzYjM4OTg4XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=U5wXKMSDks8', 6.3, 105, 'Ben Howling', ARRAY['Martin Freeman', 'Anthony Hayes'], 'Australia', 229.00, ARRAY['Netflix']),
('Apostle', 'In 1905, a drifter on a dangerous mission to rescue his kidnapped sister tangles with a sinister religious cult.', 2018, 'Horror', 'https://m.media-amazon.com/images/M/MV5BM2Y5NjI5OGEtNzU3Ny00NGNkLWEzY2MtYzEwMGM5MTZhZjhmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=rEM1_XJKqP4', 6.3, 130, 'Gareth Evans', ARRAY['Dan Stevens', 'Richard Elfyn'], 'UK', 249.00, ARRAY['Netflix']),
('Gerald\'s Game', 'A couples weekend getaway goes awry when the husband dies, leaving his wife handcuffed to their bed frame.', 2017, 'Horror', 'https://m.media-amazon.com/images/M/MV5BNmNlNTI0NjMtN2Q0ZS00Y2E5LTgwYzItNTg2NDY1NjMxOGJhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=twflAj7P-Ww', 6.5, 103, 'Mike Flanagan', ARRAY['Carla Gugino', 'Bruce Greenwood'], 'USA', 199.00, ARRAY['Netflix']),
('The Fundamentals of Caring', 'A writer retires after a personal tragedy and becomes a disabled teens caregiver.', 2016, 'Drama', 'https://m.media-amazon.com/images/M/MV5BMTQ1NDkwNzY2NV5BMl5BanBnXkFtZTgwNTAwOTgwODE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=sE_rCdZVFsI', 7.3, 97, 'Rob Burnett', ARRAY['Paul Rudd', 'Craig Roberts'], 'USA', 199.00, ARRAY['Netflix']),
('Mudbound', 'Two families, one black and one white, face farming struggles during World War II in the rural South.', 2017, 'Drama', 'https://m.media-amazon.com/images/M/MV5BMGQzNzFmNzItMWY5Mi00OTg5LTg4ZGEtMGI2YmJhNjIwZGMzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=FFh1Fl-HoP8', 7.4, 134, 'Dee Rees', ARRAY['Carey Mulligan', 'Garrett Hedlund'], 'USA', 249.00, ARRAY['Netflix']),
('Beasts of No Nation', 'A drama based on the experiences of Agu, a child soldier fighting in the civil war of an unnamed African country.', 2015, 'Drama', 'https://m.media-amazon.com/images/M/MV5BMjc0MzMzNDU0NF5BMl5BanBnXkFtZTgwOTEzMzI2NjE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=2xb9Ty-1frw', 7.7, 137, 'Cary Joji Fukunaga', ARRAY['Abraham Attah', 'Emmanuel Affadzi'], 'USA', 249.00, ARRAY['Netflix']),
('The King', 'Young Henry V encounters deceit, war and treachery after becoming King of England in the 15th century.', 2019, 'Drama', 'https://m.media-amazon.com/images/M/MV5BZmJkNTIzODgtODVjMy00ZTFlLTgyN2MtZmUxZjM1MDQ0ZGQ5XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=3HGGPOP_Z8w', 7.3, 140, 'David Michôd', ARRAY['Timothée Chalamet', 'Joel Edgerton'], 'Australia', 279.00, ARRAY['Netflix']),
('The Devil All the Time', 'Sinister characters converge around a young man devoted to protecting those he loves in a postwar backwoods town.', 2020, 'Crime', 'https://m.media-amazon.com/images/M/MV5BZjRkNWFlY2EtOTU0Mi00YzJjLWJhMzEtNzg3MDEwYjBjM2U5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=FeBlValT-cs', 7.1, 138, 'Antonio Campos', ARRAY['Tom Holland', 'Bill Skarsgård'], 'USA', 279.00, ARRAY['Netflix']),
('I Care a Lot', 'A court-appointed legal guardian defrauds her older clients and traps them under her care.', 2020, 'Crime', 'https://m.media-amazon.com/images/M/MV5BMTg4NzIyODM0NF5BMl5BanBnXkFtZTgwMTcxODY5MDE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=tD-qo0gElFI', 6.4, 118, 'J Blakeson', ARRAY['Rosamund Pike', 'Peter Dinklage'], 'UK', 249.00, ARRAY['Netflix']),
('Thunder Force', 'In a world where supervillains are commonplace, two estranged childhood best friends reunite after one devises treatment.', 2021, 'Comedy', 'https://m.media-amazon.com/images/M/MV5BYzIyN2I5NzQtYWQzMy00MzQ3LTkwN2ItODVkNTA5ZTE0ZWJmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=NZsDbKW6yG8', 4.4, 106, 'Ben Falcone', ARRAY['Melissa McCarthy', 'Octavia Spencer'], 'USA', 199.00, ARRAY['Netflix']),
('The Woman in the Window', 'An agoraphobic woman living alone in New York begins spying on her new neighbors.', 2021, 'Thriller', 'https://m.media-amazon.com/images/M/MV5BMTY1MjQwNTgwMF5BMl5BanBnXkFtZTgwMzIzNjM2NjE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=N_kstVTvN_c', 5.7, 100, 'Joe Wright', ARRAY['Amy Adams', 'Gary Oldman'], 'USA', 229.00, ARRAY['Netflix']),
('Army of the Dead', 'Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble.', 2021, 'Action', 'https://m.media-amazon.com/images/M/MV5BMTU3ODg3NTk5NF5BMl5BanBnXkFtZTgwNTA3OTY5MDE@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=tI1JGPhYBS8', 5.8, 148, 'Zack Snyder', ARRAY['Dave Bautista', 'Ella Purnell'], 'USA', 299.00, ARRAY['Netflix']),
('Sweet Tooth', 'A post-apocalyptic fairytale about a hybrid deer-boy and a wandering loner who embark on an extraordinary adventure.', 2021, 'Adventure', 'https://m.media-amazon.com/images/M/MV5BMTZkZjgxMzQtODE1Mi00YTU0LTgxOTYtOGNhZTZlODdlOWQwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=rgWGM0dJKJ0', 7.8, 45, 'Jim Mickle', ARRAY['Nonso Anozie', 'Christian Convery'], 'USA', 199.00, ARRAY['Netflix']),
('Red Notice', 'An Interpol agent tracks the worlds most wanted art thief.', 2021, 'Action', 'https://m.media-amazon.com/images/M/MV5BZmRjODgyMzEtMzIxYS00OWY2LTk4YjUtMGMzZjMzMTZiN2Q0XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg', 'https://www.youtube.com/watch?v=Pj0wz7zu3Ms', 6.3, 118, 'Rawson Marshall Thurber', ARRAY['Dwayne Johnson', 'Ryan Reynolds'], 'USA', 349.00, ARRAY['Netflix']);