-- Populate movies table with real data including IMDB ratings
INSERT INTO public.movies (title, description, genre, poster_url, trailer_link, director, cast_members, awards, imdb_rating, runtime_minutes, release_year, price, is_premium, country, streaming_platforms) VALUES
('The Dark Knight', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'Action', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=EXeTwQWrcwY', 'Christopher Nolan', ARRAY['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'], '2 Oscars, 151 wins & 159 nominations total', 9.0, 152, 2008, 399, true, 'USA', ARRAY['Prime Video', 'Netflix']),

('Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=YoHD9XEInc0', 'Christopher Nolan', ARRAY['Leonardo DiCaprio', 'Marion Cotillard', 'Tom Hardy'], '4 Oscars, 157 wins & 220 nominations total', 8.8, 148, 2010, 299, true, 'USA', ARRAY['Netflix', 'HBO Max']),

('The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'Crime', 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=sY1S34973zA', 'Francis Ford Coppola', ARRAY['Marlon Brando', 'Al Pacino', 'James Caan'], '3 Oscars, 28 wins & 30 nominations total', 9.2, 175, 1972, 249, true, 'USA', ARRAY['Prime Video', 'Hulu']),

('Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.', 'Crime', 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=s7EdQ4FqbhY', 'Quentin Tarantino', ARRAY['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'], '1 Oscar, 69 wins & 71 nominations total', 8.9, 154, 1994, 199, false, 'USA', ARRAY['Netflix', 'Prime Video']),

('Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with an IQ of 75.', 'Drama', 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=bLvqoHBptjg', 'Robert Zemeckis', ARRAY['Tom Hanks', 'Robin Wright', 'Gary Sinise'], '6 Oscars, 50 wins & 74 nominations total', 8.8, 142, 1994, 249, false, 'USA', ARRAY['Prime Video', 'Netflix']),

('The Matrix', 'A computer programmer is led to fight an underground war against powerful computers who have constructed his entire reality with a system called the Matrix.', 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=vKQi3bBA1y8', 'The Wachowskis', ARRAY['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'], '4 Oscars, 37 wins & 51 nominations total', 8.7, 136, 1999, 299, true, 'USA', ARRAY['HBO Max', 'Netflix']),

('Goodfellas', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.', 'Crime', 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjA4YTQyYzliODZiXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=qo5jJpHtI1Y', 'Martin Scorsese', ARRAY['Robert De Niro', 'Ray Liotta', 'Joe Pesci'], '1 Oscar, 42 wins & 37 nominations total', 8.7, 146, 1990, 199, false, 'USA', ARRAY['Prime Video', 'Netflix']),

('Fight Club', 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much more.', 'Drama', 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=qtRKdVHc-cE', 'David Fincher', ARRAY['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'], 'Nominated for 1 Oscar, 12 wins & 38 nominations total', 8.8, 139, 1999, 249, true, 'USA', ARRAY['Netflix', 'Hulu']),

('Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity survival.', 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=zSWdZVtXT7E', 'Christopher Nolan', ARRAY['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'], '1 Oscar, 44 wins & 148 nominations total', 8.6, 169, 2014, 349, true, 'USA', ARRAY['Prime Video', 'HBO Max']),

('The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'Drama', 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'https://www.youtube.com/watch?v=6hB3S9bIaco', 'Frank Darabont', ARRAY['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'], 'Nominated for 7 Oscars, 21 wins & 35 nominations total', 9.3, 142, 1994, 199, false, 'USA', ARRAY['Prime Video', 'Netflix']);